<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-02-11 21:20
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-02-11 12:30
from __future__ import unicode_literals
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=800)),
                ('estate_logo', models.ImageField(default='test.png', upload_to='images')),
                ('description', models.TextField()),
=======
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('product_type', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('profile_pic', models.ImageField(upload_to='profile/')),
>>>>>>> master
            ],
        ),
    ]
