# Generated by Django 3.1.5 on 2021-02-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmerch',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
        migrations.AlterField(
            model_name='productmerch',
            name='description',
            field=models.TextField(default='Empty description.', max_length=500),
        ),
    ]
