# Generated by Django 3.1.5 on 2021-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=40)),
                ('product_type', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('profile_pic', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
