# Generated by Django 3.1.5 on 2021-02-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210215_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmerch',
            name='category',
        ),
        migrations.AddField(
            model_name='productmerch',
            name='category',
            field=models.TextField(default='Empty description.', max_length=500),
        ),
    ]
