# Generated by Django 3.1.5 on 2021-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=800)),
                ('estate_logo', models.ImageField(default='test.png', upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='profile_pic',
        ),
    ]
