# Generated by Django 3.1.5 on 2021-02-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
