# Generated by Django 3.1.5 on 2021-02-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210222_1528'),
        ('app', '0006_auto_20210223_1203'),
    ]

    operations = [
    ]
